### PR TITLE
Make `cloud` a true dependency of `cloud-aws`.

### PR DESCRIPTION
**Pull request by lukehoban**
Since we depend on types exposed in `cloud`, this needs to be available - and we don't want to push the burden of installing it to users via `peerDepdencies`.

### CODE REVIEW

**Comment by lukehoban** [comment]
@ellismg From my read of the scripts that replace `${VERSION}` it's not clear to me why this is failing.  Any idea?

**Comment by ellismg** [comment]
> @ellismg From my read of the scripts that replace ${VERSION} it's not clear to me why this is failing. Any idea?

Yes, I understand what is going on here.  We do not replace `${VERSION}` in the `package.json` file we have checked in.  We only do that in the one we generate in the bin folder (we do this because otherwise the source package.json file would get changed on every build).  Even if we did change the version before, we'd have problems trying to restore dependencies for the project, because it would refer to a version of the package which was not yet on NPM.

We have technology that promotes a peerDependency to a real dependency before we actually publish the package. I've used that in in e4a7126.

**Comment by lukehoban** [comment]
> We have technology that promotes a peerDependency to a real dependency before we actually publish the package. I've used that in in e4a7126.

Okay - so if I follow e4a7126, then this issue is fixed and I can close this PR?

**Comment by ellismg** [comment]
Sorry, I pushed the commit I referenced as part of this PR.  I believe if we merge the PR as is, then we will have fixed the issue.

**Comment by joeduffy** [comment]
@ellismg Plan to merge for 0.15?

**Pull request merged**
