### PR TITLE
Test docker change.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by ellismg** [comment]
Can I leave a comment?

**Comment by CyrusNajmabadi** [comment]
Tagging @mazamats

**Comment by mazamats** [comment]
@CyrusNajmabadi 

```
[ lumi-cloud/examples/containers ]     error: Plan apply failed: Error creating Application Load Balancer: TooManyLoadBalancers: The maximum number of load balancers has been reached
```

**Comment by CyrusNajmabadi** [comment]
@mazamats Looks like we have a lot of tests in flight right now.  When this dies down i have a script that helps clear this out.  then i'll rerun this. T hanks1

**Comment by CyrusNajmabadi** [comment]
@mazamats Looks like this does cause a regression:

> [ lumi-cloud/examples/containers ]  +  cloud:service:Service examples-multistage-cached-nginx creating warning: Error response from daemon: manifest for 086028354146.dkr.ecr.us-east-2.amazonaws.com/pulum-b3285f40-container-81c631d:build not found

**Comment by mazamats** [comment]
@CyrusNajmabadi The failure is still AWS related.

The output you posted comes up as a `warning` and not an error, this is where its coming from https://github.com/pulumi/pulumi-docker/blob/1fe8e7221f6d203eaa67940235f81ed7b8224bd9/docker/docker.ts#L261-L299

```
[ lumi-cloud/examples/containers ] Diagnostics:
[ lumi-cloud/examples/containers ]   pulumi:pulumi:Stack (containers-containers-ec2-749503f8):
[ lumi-cloud/examples/containers ]     flag provided but not defined: -tracing
[ lumi-cloud/examples/containers ]     Usage of tf-provider-flags:
[ lumi-cloud/examples/containers ]       -get-provider-info
[ lumi-cloud/examples/containers ]         	dump provider info as JSON to stdout
[ lumi-cloud/examples/containers ]  
[ lumi-cloud/examples/containers ]   cloud:service:Service (examples-cached-nginx):
[ lumi-cloud/examples/containers ]     warning: Error response from daemon: manifest for 086028354146.dkr.ecr.us-east-2.amazonaws.com/pulum-164fa748-container-4a9a77f:latest not found
[ lumi-cloud/examples/containers ]  
[ lumi-cloud/examples/containers ]   aws:apigateway:VpcLink (examples-containers7d5cd3e1):
[ lumi-cloud/examples/containers ]     error: Plan apply failed: BadRequestException: There are too many Vpc Links defined for this account. Limit is 5
[ lumi-cloud/examples/containers ]     	status code: 400, request id: e4abfeaa-ea15-11e8-85c5-fde775023fbb
[ lumi-cloud/examples/containers ]  
[ lumi-cloud/examples/containers ]   cloud:service:Service (examples-multistage-cached-nginx):
[ lumi-cloud/examples/containers ]     warning: Error response from daemon: manifest for 086028354146.dkr.ecr.us-east-2.amazonaws.com/pulum-b3285f40-container-81c631d:build not found
[ lumi-cloud/examples/containers ]  
[ lumi-cloud/examples/containers ]     warning: Error response from daemon: manifest for 086028354146.dkr.ecr.us-east-2.amazonaws.com/pulum-b3285f40-container-81c631d:latest not found
[ lumi-cloud/examples/containers ]  
[ lumi-cloud/examples/containers ] Resources:
[ lumi-cloud/examples/containers ]     75 changes
[ lumi-cloud/examples/containers ]     + 75 created
```

**Comment by CyrusNajmabadi** [comment]
Closing out.

**Pull request closed without merging**
